name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or main, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create static site directory
        run: |
          mkdir -p build
          cp -r website/static/* build/
          cp -r website/templates/* build/
          
      - name: Convert relative paths
        run: |
          # Update paths in HTML files to be relative
          find build -type f -name "*.html" -exec sed -i 's/\/static\//./g' {} +
          # If you have any other path adjustments, add them here
          
      - name: Add index.html if not exists
        run: |
          if [ ! -f build/index.html ]; then
            mv build/home.html build/index.html || true
            mv build/main.html build/index.html || true
          fi

      # Optional: Run any build scripts here if you need to generate additional static content
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

# Environment settings
env:
  # Update this if you're using a custom domain
  BASE_URL: ""  # Example: /your-repo-name